#type:        string
#description: the file name to record connd PID
#default:     titan.pid
#pid-filename = "titan.pid"

[server]

#type:        string
#description: client connetion auth
auth = ""

#type:        string
#rules:       netaddr
#description: address to listen
#default:     0.0.0.0:7369
#listen = "0.0.0.0:7369"

#type:        string
#description: server SSL certificate file (enables SSL support)
ssl-cert-file = ""

#type:        string
#description: server SSL key file
ssl-key-file = ""

#type:        int64
#rules:       numeric
#description: client connection count
#default:     1000
#max-connection = 1000

#type:        int
#rules:       numeric
#description: the max limit length of elements in list
#default:     100
#list-zip-threshold = 100


[status]

#type:        string
#rules:       nonempty
#description: listen address of http server
#default:     0.0.0.0:7345
#listen = "0.0.0.0:7345"

#type:        string
#description: status server SSL certificate file (enables SSL support)
ssl-cert-file = ""

#type:        string
#description: status server SSL key file
ssl-key-file = ""


[tikv]

#type:        string
#description: pd address in tidb
#required
##mocktikv是内存模式
pd-addrs = "mocktikv://"

[tikv.db]

[tikv.db.hash]

#type:        int64
#rules:       numeric
#description: hashes slot key count
#default:     0
#meta-slot = 0


[tikv.gc]

#type:        bool
#rules:       boolean
#description: false is used to disable gc
#default:     false
#disable = false

#type:        time.Duration
#description: gc work tick interval
#default:     1s
#interval = "1s"

#type:        time.Duration
#description: lease flush leader interval
#default:     3m
#leader-life-time = "3m0s"

#type:        int
#rules:       numeric
#description: key count limitation per-transection
#default:     256
#batch-limit = 256


[tikv.expire]

#type:        bool
#rules:       boolean
#description: false is used to disable expire
#default:     false
#disable = false

#type:        time.Duration
#description: expire work tick interval
#default:     1s
#interval = "1s"

#type:        time.Duration
#description: lease flush leader interval
#default:     3m
#leader-life-time = "3m0s"

#type:        int
#rules:       numeric
#description: key count limitation per-transection
#default:     256
#batch-limit = 256


[tikv.zt]

#type:        bool
#rules:       boolean
#description: false is used to disable  zt
#default:     false
#disable = false

#type:        int
#rules:       numeric
#description: parallel workers count
#default:     5
#workers = 5

#type:        int
#rules:       numeric
#description: object transfer limitation per-transection
#default:     10
#batch = 10

#type:        int
#rules:       numeric
#description: ZT Worker queue depth
#default:     100
#depth = 100

#type:        time.Duration
#description: Queue fill interval in milsecond
#default:     1000ms
#interval = "1s"


[tikv.tikv-gc]

#type:        bool
#rules:       boolean
#description: false is used to disable tikvgc
#default:     false
#disable = false

#type:        time.Duration
#description: gc work tick interval
#default:     20m
#interval = "20m0s"

#type:        time.Duration
#description: lease flush leader interval
#default:     30m
#leader-life-time = "30m0s"

#type:        time.Duration
#description: safe point life time
#default:     10m
#safe-point-life-time = "10m0s"

#type:        int
#description: gc work concurrency
#default:     2
#concurrency = 2

[tikv.rate-limit]
#type:        string
#default:     eth0
#description: the interface name to get ip and write local titan status to tikv for balancing rate limit
interface-name = "eth0"

#type:        string
#default:     sys_ratelimit
#the namespace of getting limit/balance data
#limiter-namespace = "sys_ratelimit"

#type:        time.Duration
#description: the period in seconds to balance rate limiting with other titan nodes
#default:     15s
#global-balance-period = "15s"

#type:        time.Duration
#description: how long if a titan didn't update its status, we consider it dead
#default:     1m
#titanstatus-life-time = "1m"

#type:        time.Duration
#description: the period in seconds to sync new limit set in tikv
#default:     3s
#sync-set-period = "3s"

[tikv-logger]

#type:        string
#rules:       nonempty
#description: the default log path
#default:     logs/tikv
#path = "logs/tikv"

#type:        string
#description: log level(debug, info, warn, error, panic, fatal)
#default:     info
#level = "info"

#type:        bool
#rules:       boolean
#description: true for enabling log compress
#default:     false
#compress = false

#type:        string
#description: log time rotate pattern(s m h D M W)
#default:     0 0 0 * * *
#time-rotate = "0 0 0 * * *"


[logger]

#type:        string
#description: the default logger name
#default:     titan
#name = "titan"

#type:        string
#description: the default log path
#default:     logs/titan
#path = "logs/titan"

#type:        string
#description: log level(debug, info, warn, error, panic, fatal)
#default:     info
#level = "info"

#type:        bool
#rules:       boolean
#description: true for enabling log compress
#default:     false
#compress = false

#type:        string
#description: log time rotate pattern(s m h D M W)
#default:     0 0 0 * * *
#time-rotate = "0 0 0 * * *"

