{
 "title": "Titan-Server",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "jobname", "label": "服务类型", "query": "titan" },
   { "name": "biz", "label": "biz", "query": "thor" },
   { "name": "group", "query": "thor" }
  ]
 },
 "panels": [
  { "title": "Titan", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Leaders",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "titan_is_leader{job=\"$jobname\",group=\"$group\"}",
     "legendFormat": "{{instance}}/{{leader}}"
    }
   ]
  },
  {
   "title": "在线连接计数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(titan_connect_online_number{job=\"$jobname\",biz = \"$biz\"})by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LRange seek start 耗时 0.99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(titan_lrange_seek_duration_seconds_bucket{biz=~\"$biz\",job=\"$jobname\"}[1m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "事务提交耗时(99)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(titan_txn_commit_seconds_bucket{biz=~\"$biz\",job=\"$jobname\"}[1m])) by (le,command))",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "命令调用计数 /s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(titan_command_duration_seconds_count{biz=~\"$biz\",job=\"$jobname\"}[1m]))by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "命令调用耗时(99)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(titan_command_duration_seconds_bucket{biz=~\"$biz\",job=\"$jobname\"}[1m])) by (le,command))",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "GC 调用计数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(titan_gc_keys_total{job=\"$jobname\",group=\"$group\"}[20s]))by (gckeys)",
     "legendFormat": "{{gckeys}}"
    }
   ]
  },
  {
   "title": "事务重试计数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "事务失败调用计数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(titan_txn_failures_total{biz=~\"$biz\",job=\"$jobname\"}[20s]))by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "事务冲突调用计数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(titan_txn_conflicts_total{biz=~\"$biz\",job=\"$jobname\"}[20s]))by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": " command per exec count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(titan_multi_command_total_sum{biz=~\"$biz\",job=\"$jobname\"}[20s]))/sum(rate(titan_multi_command_total_count{biz=~\"$biz\",job=\"$jobname\"}[20s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.999,sum(rate(titan_multi_command_total_bucket{biz=~\"$biz\",job=\"$jobname\"}[20s]))by (le))",
     "legendFormat": "999"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(titan_multi_command_total_bucket{biz=~\"$biz\",job=\"$jobname\"}[20s]))by(le))",
     "legendFormat": "99"
    }
   ]
  },
  {
   "title": "ZT Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "ZT Qps",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ]
    },
    {
     "title": "ZT keys flow",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(titan_zt_info_total{ztinfo=\"key\",job=\"$jobname\"}[30s])) by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "ZT total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(titan_zt_info_total{ztinfo=\"zlist\",job=\"$jobname\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "ZT keys total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(titan_zt_info_total{ztinfo=\"key\",job=\"$jobname\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SDK KV Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "KV Request Duration 999 by store",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9999, sum(rate(tidb_tikvclient_request_seconds_bucket{type!=\"GC\",job=\"$jobname\",group=\"$group\"}[1m])) by (le, store))",
       "legendFormat": "store-{{store}}"
      }
     ]
    },
    {
     "title": "KV Request Duration 999 by type",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(tidb_tikvclient_request_seconds_bucket{type!=\"GC\",job=\"$jobname\",group=\"$group\"}[1m])) by (le,type))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "KV Cmd Duration 9999",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(tidb_tikvclient_txn_cmd_duration_seconds_bucket{job=\"$jobname\",group=\"$group\"}[1m])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "KV Cmd Duration 99",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_tikvclient_txn_cmd_duration_seconds_bucket{job=\"$jobname\",group=\"$group\"}[1m])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SDK KV Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "KV Retry Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9999, sum(rate(tidb_tikvclient_backoff_seconds_bucket{job=\"$jobname\",grop=\"$group\"}[1m])) by (le))",
       "legendFormat": "9999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_tikvclient_backoff_seconds_bucket{job=\"$jobname\",group=\"$group\"}[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(tidb_tikvclient_backoff_seconds_bucket{job=\"$jobname\",group=\"$group\"}[1m])) by (le))",
       "legendFormat": "80"
      }
     ]
    },
    {
     "title": "TiClient Region Error OPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_region_err_total{job=\"$jobname\",group=\"$group\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "KV Backoff OPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_backoff_total{job=\"$jobname\",group=\"$group\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Lock Resolve OPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_lock_resolver_actions_total{job=\"$jobname\",group=\"$group\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Other Errors OPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_lock_cleanup_task_total{job=\"$jobname\",group=\"$group\"}[1m])) by (type)",
       "legendFormat": "cleanup_secondary_failure_{{type}}"
      },
      {
       "expr": "sum(rate(tidb_tikvclient_load_safepoint_total{type=\"fail\",job=\"$jobname\",group=\"$group\"}[1m]))",
       "legendFormat": "load_safepoint_failure"
      }
     ]
    }
   ]
  },
  {
   "title": "SDK KV Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "KV Cmd OPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_txn_cmd_duration_seconds_count{job=\"$jobname\",group=\"$group\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "KV Txn OPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_txn_total{job=\"$jobname\",group=\"$group\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Txn Regions Num 90",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(tidb_tikvclient_txn_regions_num_bucket{job=\"$jobname\",group=\"$group\"}[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Txn Write Size Bytes 100",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tidb_tikvclient_txn_write_size_bytes_bucket{job=\"$jobname\",group=\"$group\"}[1m])) by (le, instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Txn Write KV Num 100",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1, sum(rate(tidb_tikvclient_txn_write_kv_num_bucket{job=\"$jobname\",group=\"$group\"}[1m])) by (le, instance))",
       "legendFormat": "100 {{instance}}"
      }
     ]
    },
    {
     "title": "Load Safepoint OPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_load_safepoint_total{type=\"ok\",job=\"$jobname\",group=\"$group\"}[1m]))by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PD Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "PD Client CMD OPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_client_cmd_handle_cmds_duration_seconds_count{type!=\"tso\",job=\"$jobname\",group=\"$group\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "PD Client CMD Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type!=\"tso\",job=\"$jobname\",group=\"$group\"}[1m])) by (le, type))",
       "legendFormat": "999-{{type}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type!=\"tso\",job=\"$jobname\",group=\"$group\"}[1m])) by (le, type))",
       "legendFormat": "99-{{type}}"
      }
     ]
    },
    {
     "title": "PD Client CMD Fail OPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_client_cmd_handle_failed_cmds_duration_seconds_count{job=\"$jobname\",group=\"$group\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "PD TSO OPS",
     "type": "graph",
     "description": "The duration of a client calling GetTSAsync until received the TS result.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pd_client_cmd_handle_cmds_duration_seconds_count{type=\"tso\",job=\"$jobname\"}[1m]))",
       "legendFormat": "cmd"
      },
      {
       "expr": "sum(rate(pd_client_request_handle_requests_duration_seconds_count{type=\"tso\",job=\"$jobname\"}[1m]))",
       "legendFormat": "request"
      }
     ]
    },
    {
     "title": "PD TSO Wait Duration",
     "type": "graph",
     "description": "The duration of a client calling GetTSAsync until received the TS result.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type=\"tso\",job=\"$jobname\",group=\"$group\"}[1m])) by (le))",
       "legendFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type=\"tso\",job=\"$jobname\",group=\"$group\"}[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    },
    {
     "title": "PD TSO RPC Duration",
     "type": "graph",
     "description": "The duration of a client sending TSO request until received the response.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(pd_client_request_handle_requests_duration_seconds_bucket{type=\"tso\",job=\"$jobname\",group=\"$group\"}[1m])) by (le))",
       "legendFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_client_request_handle_requests_duration_seconds_bucket{type=\"tso\",job=\"$jobname\",group=\"$group\"}[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    }
   ]
  },
  {
   "title": "GRPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "grpc_client_started_total",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_client_started_total{grpc_method!=\"KvScan\",job=\"$jobname\",group=\"$group\"}[30s])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "grpc_client_msg_sent_total",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_client_msg_sent_total{job=\"$jobname\",grpc_method!=\"KvScan\",group=\"$group\"}[30s])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    },
    {
     "title": "grpc_client_handled_total",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(grpc_client_handled_total{job=\"$jobname\",grpc_method!=\"KvScan\",group=\"$group\"}[30s])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TikvGC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Worker Actions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_gc_worker_actions_total{group=\"$group\",job=\"$jobname\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "gc Seconds",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum(rate(tidb_tikvclient_gc_seconds_bucket[1m])) by (instance, le))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "goroutine个数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{group=\"$group\",job=\"$jobname\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "日志级别 率",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(titan_logs_entries_total{job=\"$jobname\",group=\"$group\"}[1m])) by (level)",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Go GC耗时（抽样平均）",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(go_gc_duration_seconds_sum{group=\"thor\",job=\"$jobname\"}[20s])/rate(go_gc_duration_seconds_count{group=\"thor\",job=\"$jobname\"}[20s])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "内存使用",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{group=\"$group\",job=\"$jobname\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Heap对象计数",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_objects{group=\"$group\",job=\"$jobname\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "空闲但未归还内存（Heap Idle）",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_idle_bytes{group=\"$group\",job=\"$jobname\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}